Connect4
GAIGResearch/TabletopGames pull request #211
Opened 2022-09-08 17:22 UTC by GAIGResearch

A classic: Connect 4. Game heuristic is a simple win/lose heuristic.

2022-09-08 19:17 UTC, rdgain requested changes
A couple of small changes, the rest is approved.

2022-09-08 19:17 UTC, rdgain commented on src/main/java/games/connect4/Connect4Constants.java
> +    public static final int winCount = 4;
Parameter please :)

2022-09-08 19:17 UTC, rdgain commented on src/main/java/games/connect4/Connect4GameState.java
> +    public void registerWinningCells(LinkedList<Pair<Integer, Integer>> winnerCells) {
Package private?

2022-09-09 08:44 UTC, GAIGResearch commented on src/main/java/games/connect4/Connect4Constants.java
> +    public static final int winCount = 4;
Done.

2022-09-09 08:44 UTC, GAIGResearch commented on src/main/java/games/connect4/Connect4GameState.java
> +    public void registerWinningCells(LinkedList<Pair<Integer, Integer>> winnerCells) {
Done.

2022-09-09 09:31 UTC, rdgain approved these changes

2022-09-09 09:57 UTC, merged