Chinesecheckers
GAIGResearch/TabletopGames pull request #255
Opened 2023-09-06 11:06 UTC by hopshackle

Chinese Checkers implementation

2023-09-20 15:11 UTC, rdgain requested changes

2023-10-18 10:35 UTC, hopshackle commented on src/main/java/games/chinesecheckers/CCHeuristic.java
> +            for(int i = 111; i <= 120; i++){
thank you!

2023-10-18 10:43 UTC, hopshackle commented on src/main/java/games/chinesecheckers/CCGameState.java
> +        if (nPlayers == 5) {
Not quite - CC supports 2, 3, 4, 6 players....and the framework only support a range of (min, max)

2023-10-18 10:44 UTC, hopshackle commented on src/main/java/games/chinesecheckers/CCParameters.java
> +    public Map<Integer, Peg.Colour[]> playerColours = new HashMap<>();
Not sure I understand this comment.

2023-10-18 10:57 UTC, hopshackle commented on src/main/java/games/chinesecheckers/components/CCNode.java
> +    public void setMaxNeighbours(int maxNeighbours) {
There is no superclass as such - it is far worse than that. 
To get this to work we had to cut-and-paste another example and then modify it....but you are right there is a lot of cut-and-paste cruft; now surgically removed where possible.

2023-10-18 10:57 UTC, hopshackle commented on src/main/java/games/chinesecheckers/components/StarBoard.java
> +        for(int i = 0; i < 121; i++) {this.getBoardNodes().add(new CCNode(i));}
Probably not without breaking it. Ugly, but it works.

2023-10-18 11:02 UTC, hopshackle commented on src/main/java/games/chinesecheckers/components/StarBoard.java
> +        for(int i = 0; i <= 9; i++){
Yes - it can be prettified, and the cost of a small hack on parameter accessibility. Done.

2023-10-18 11:14 UTC, hopshackle commented on src/main/java/games/chinesecheckers/gui/CCGraphView.java
> +        if(((CCNode)starBoard.getBoardNodes().get(node.getID())).getBaseColour().name() == "purple"){
There is indeed an easier and clearer way. Now implemented.

2023-10-18 11:18 UTC, rdgain commented on src/main/java/games/chinesecheckers/CCGameState.java
> +        if (nPlayers == 5) {
Oh I see! Makes sense

2023-10-19 12:01 UTC, rdgain approved these changes

2023-10-20 15:36 UTC, merged