Hearts
GAIGResearch/TabletopGames pull request #256
Opened 2023-09-06 11:07 UTC by hopshackle

Implementation of Hearts

2023-09-20 15:25 UTC, rdgain requested changes

2023-09-20 15:25 UTC, rdgain commented on src/main/java/games/hearts/HeartsForwardModel.java
> +        cardsToRemove.put(3, Arrays.asList(new FrenchCard(FrenchCard.FrenchCardType.Number, FrenchCard.Suite.Diamonds, 2)));
Lots of hardcoded numbers.

2023-09-20 15:25 UTC, rdgain commented on src/main/java/games/hearts/HeartsForwardModel.java
> +        int numberOfCards;
Parameter

2023-09-20 15:25 UTC, rdgain commented on src/main/java/games/hearts/HeartsForwardModel.java
> +        cardsToRemove.put(3, Arrays.asList(new FrenchCard(FrenchCard.FrenchCardType.Number, FrenchCard.Suite.Diamonds, 2)));
Everywhere!

2023-09-20 15:25 UTC, rdgain commented on src/main/java/games/hearts/HeartsGameState.java
> +            addAll(playerDecks);
Not all are listed?

2023-09-20 15:25 UTC, rdgain commented on src/main/java/games/hearts/HeartsGameState.java
> +                    else if (card.suite == FrenchCard.Suite.Spades && card.number == 12) {
Hard-coded number?

2023-10-18 10:34 UTC, hopshackle commented
Various things now parameterised, and getAllComponents now does.

2023-10-20 14:27 UTC, rdgain commented on src/main/java/games/hearts/HeartsForwardModel.java
> +                if (cardsPassed == 3) {
One more parameter

2023-10-20 14:27 UTC, rdgain commented on src/main/java/games/hearts/HeartsForwardModel.java
> +            boolean scoreAbove100 = hgs.playerPoints.values().stream().anyMatch(score -> score >= 100);
And this one too.

2023-10-20 14:48 UTC, hopshackle commented on src/main/java/games/hearts/HeartsForwardModel.java
> +                if (cardsPassed == 3) {
Damn - missed that.

2023-10-20 14:48 UTC, hopshackle commented on src/main/java/games/hearts/HeartsForwardModel.java
> +            boolean scoreAbove100 = hgs.playerPoints.values().stream().anyMatch(score -> score >= 100);
and that one!

2023-10-20 15:20 UTC, rdgain approved these changes

2023-10-20 15:24 UTC, merged