Mastermind
GAIGResearch/TabletopGames pull request #287
Opened 2024-07-23 14:52 UTC by cayenwang

Implemented Mastermind

2024-07-26 12:58 UTC, hopshackle requested changes
Looks very good - main point is to remove the Cluedo code from this PR to avoid putting a half-finished game into the main repository.

2024-07-26 12:58 UTC, hopshackle commented on src/main/java/games/GameType.java
> +    Cluedo(2,6,
The pull request should just contain Mastermind (and any core changes required to support it). Cluedo is still in development so should be kept in its own branch.

2024-07-26 12:58 UTC, hopshackle commented on src/main/java/games/mastermind/MMGameState.java
> +    public double getGameScore(int playerId) {
getGameScore should be reserved for an actual game score as per the rules of the game - which you can argue in Mastermind is equal to the number of rows unused. (Or, that there is no concept of score, in which case always return 0).

The code here is for a (very reasonable) heuristic.

2024-07-30 09:41 UTC, cayenwang commented
I've implemented the changes. Not sure if I need to re-mark this PR as 'ready for review'

2024-08-23 09:38 UTC, merged