Saboteur
GAIGResearch/TabletopGames pull request #293
Opened 2024-09-24 15:34 UTC by rdgain

By (Gavin Hor, 2024 QMUL UG Project)

A couple of things still to do:
- [x] Make sure the game actually runs as intended (it does run, but *correctly*?)
- [x] Make a GUI

2024-12-24 17:02 UTC, hopshackle commented
I haven't at this stage looked at the Saboteur code at all (let me know if you want me to), but have focused on the more general changes.
The main problem is backwards compatibility of the GridBoard changes - the (ForwardModelTester) unit tests for TicTacToe and Connect4 crash and burn; the immediate issue seems to be in checking game end, and the emptyCell Constant. Also, my OMA/Tree Reuse/MultiMCTS unit tests are seas of red for the same issue, as TicTacToe is a wonderfully controllable environment for these.
A couple of other minor points, but that's the main one. 

(Oh, and Saboteur has some random player FM tests; but none with MCTS, which is often quite good at finding more abstruse issues)

2024-12-24 17:02 UTC, hopshackle requested changes

2024-12-26 11:28 UTC, hopshackle commented
Further quick note that I forgot to add. The two Catan forward model tests that fail due to missing json are now resolved in the master branch (so ignore those).
The Mastermind forward model tests don't actually terminate - there seems to be an infinite loop in there somewhere (I gave up at 2.5 minutes for even one game to finish).

2025-01-12 12:29 UTC, rdgain commented on src/main/java/core/Game.java
> +            forwardModel.computeAvailableActions(gameState);
I find it very useful for debugging to figure out why there are no actions available. An exception is thrown right after so it's not hurting anything :)

2025-01-12 12:53 UTC, rdgain commented
Test, yes! I did check those. And fixed the issues now, they look happy.

2025-01-19 15:57 UTC, hopshackle approved these changes
1) Fixed Mastermind to work properly with Token Type.
2) I also had Saboteur throwing warnings when using MCTS with ForwardModel testing. The cause of this was duplicate actions being generated. I fixed this by changing the saboteur game state list of path options to be a Set<> instead of a List<>, so the problem is that a location could be added more than once ... not sure where though,

The second point above may be worth some extra scrutiny as my fix is really of the symptom than the root cause - there may be some 'leakage' somewhere that is not properly clearing the path list, hence allowing duplicates to be added.

However, if you're happy with this, then I'm happy.

2025-01-23 09:57 UTC, merged